[phases.setup]
nixPkgs = { python = "python311" }

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn oden_site.wsgi:application --bind 0.0.0.0:$PORT"

